# Generated by Django 5.0.1 on 2024-01-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
