# Generated by Django 5.0.1 on 2024-01-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0006_agreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.DeleteModel(
            name='Agreement',
        ),
    ]
