# Generated by Django 5.0.1 on 2024-01-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0007_remove_agreement_tenant_remove_agreement_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('document_proofs', models.FileField(upload_to='tenant_documents/')),
            ],
        ),
    ]
